"""
This type stub file was generated by pyright.
"""

import numpy as np
from typing import Any, Protocol, TYPE_CHECKING
from speech_recognition.audio import AudioData

if TYPE_CHECKING:
    ...
class Transcribable(Protocol):
    def transcribe(self, audio_array: np.ndarray, **kwargs) -> str | dict[str, Any]:
        ...
    

class WhisperCompatibleRecognizer:
    def __init__(self, model: Transcribable) -> None:
        ...
    
    def recognize(self, audio_data: AudioData, show_dict: bool = ..., **kwargs): # -> str | dict[str, Any] | Any:
        ...
    