"""
This type stub file was generated by pyright.
"""

from typing import Literal, TypedDict
from typing_extensions import Unpack
from speech_recognition.audio import AudioData

GroqModel = Literal["whisper-large-v3-turbo", "whisper-large-v3", "distil-whisper-large-v3-en"]
class GroqOptionalParameters(TypedDict):
    """Groq speech transcription's optional parameters.

    https://console.groq.com/docs/speech-text#transcription-endpoint-usage
    """
    prompt: str
    response_format: str
    temperature: float
    language: str
    ...


def recognize(recognizer, audio_data: AudioData, *, model: GroqModel = ..., **kwargs: Unpack[GroqOptionalParameters]) -> str:
    """Performs speech recognition on ``audio_data`` (an ``AudioData`` instance), using the Groq Whisper API.

    This function requires login to Groq; visit https://console.groq.com/login, then generate API Key in `API Keys <https://console.groq.com/keys>`__ menu.

    Detail: https://console.groq.com/docs/speech-text

    Set environment variable ``GROQ_API_KEY``; otherwise groq library will raise a ``groq.GroqError``.
    """
    ...