"""
This type stub file was generated by pyright.
"""

from typing import Literal
from typing_extensions import Unpack
from speech_recognition.audio import AudioData

WhisperModel = Literal["whisper-1", "gpt-4o-transcribe", "gpt-4o-mini-transcribe"]
class OpenAIOptionalParameters:
    """OpenAI speech transcription's optional parameters.

    https://platform.openai.com/docs/api-reference/audio/createTranscription
    """
    language: str
    prompt: str
    response_format: Literal["json"]
    temperature: float
    ...


def recognize(recognizer, audio_data: AudioData, *, model: WhisperModel = ..., **kwargs: Unpack[OpenAIOptionalParameters]) -> str:
    """Performs speech recognition on ``audio_data`` (an ``AudioData`` instance), using the OpenAI Whisper API.

    This function requires an OpenAI account; visit https://platform.openai.com/signup, then generate API Key in `User settings <https://platform.openai.com/account/api-keys>`__.

    Detail: https://platform.openai.com/docs/guides/speech-to-text

    Set environment variable ``OPENAI_API_KEY``; otherwise openai library will raise a ``openai.OpenAIError``.
    """
    ...

if __name__ == "__main__":
    parser = ...
    args = ...
    audio_data = ...
    recognize_args = ...
    transcription = ...