"""
This type stub file was generated by pyright.
"""

class SetupError(Exception):
    ...


class WaitTimeoutError(Exception):
    ...


class RequestError(Exception):
    ...


class UnknownValueError(Exception):
    ...


class TranscriptionNotReady(Exception):
    ...


class TranscriptionFailed(Exception):
    ...