"""
This type stub file was generated by pyright.
"""

from speech_recognition.audio import AudioData

logger = ...
class OpenAICompatibleRecognizer:
    def __init__(self, client) -> None:
        ...
    
    def recognize(self, audio_data: AudioData, model: str, **kwargs) -> str:
        ...
    